
name: 'hinge_health'
version: '1.0.0'


profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"


seeds:
  hinge_health:
    +schema: public


models:
  hinge_health:
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts
    data_quality:
      +schema: data_quality
